version: 2
jobs:
  runs:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/puchi_circleci
    steps:
      - checkout
      - run:
          name: mkdir > dist
          command: |
            mkdir dist
            mkdir dist/ja_JP
            mkdir dist/en_US
            mkdir dist/ko_KR
      - run:
          name: JP | .po to .mo
          command: msgfmt ./ja_JP/messages.po -o ./dist/ja_JP/messages.mo
      - run:
          name: EN | .po to .mo
          command: msgfmt ./en_US/messages.po -o ./dist/en_US/messages.mo
      - run:
          name: KR | .po to .mo
          command: msgfmt ./ko_KR/messages.po -o ./dist/ko_KR/messages.mo
      - store_artifacts:
          path: ~/puchi_circleci/dist/
workflows:
  version: 2
  build_and_tests:
    jobs:
      - runs:
          filters:
            branches:
              only: master
